import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { ClientProvider, AuthProvider } from "@lib/providers";
import { Footer, Header } from "@lib/components";
import type { ReactNode } from "react";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const inter = Inter({
	subsets: ["latin"],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<AuthProvider>
					<ClientProvider>
						<main className="bg-slate-50 dark:bg-black min-h-screen w-full transition-all sm:p-8 xs:p-4 p-2">
							<Header />
							<section className="p-4">{children}</section>
							<Footer />
							<Toaster
								position="bottom-right"
								toastOptions={{
									className: "!bg-slate-100 !text-slate-900 dark:!bg-slate-900 dark:!text-white",
								}}
							/>
						</main>
					</ClientProvider>
				</AuthProvider>
			</body>
		</html>
	);
}
