import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import { ClientProvider } from "@lib/providers";
import "./globals.css";
import { Footer, Header } from "@lib/components";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const inter = Inter({
	subsets: ["latin"],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<ClientProvider>
					<main className="bg-slate-50 dark:bg-black min-h-screen w-full transition-all sm:p-8 p-4">
						<Header />
						<section className="p-4">{children}</section>
						<Footer />
						<Toaster
							position="bottom-right"
							toastOptions={{
								className: "!bg-slate-100 !text-slate-900 dark:!bg-slate-900 dark:!text-white",
							}}
						/>
					</main>
				</ClientProvider>
			</body>
		</html>
	);
}
