services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      args:
        - cfg_file=dev.conf
    ports:
      - "80:80"
    networks:
      - carbon-nexus-network

networks:
  carbon-nexus-network:
    driver: bridge